name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - imbalanced-learn=0.12.4
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - llvm-openmp=14.0.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.4.0
  - pip=24.2
  - python=3.10.16
  - readline=8.2
  - scikit-learn=1.1.3
  - scipy=1.12.0
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
